### ISSUE TITLE
strong-deploy usage should have help for how to provide credentials for an authenticated pm server 

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-deploy#21]
For git deploy, user will be asked for cred by the git command prompt. 
For tar ball deploy there are no instructions on how to provide credentials

**Comment by cgole** [comment]
instead of HTTP Code: 401 say authentication failure or something similar

**Comment by rmg** [comment]
TODO:
 * [ ] Add help text about how to specify credentials.
 * [ ] Mention `--help` in the error message when we see a 401 or 403.

**Comment by rmg** [comment]
@cgole I've merged #22 and it should be available on staging soon for you to verify.

**Comment by rmg** [comment]
Released, strong-deploy@1.1.4
