### ISSUE TITLE
async should be regular dependency

### ISSUE THREAD

**Issue by alexgorbatchev** [strongloop/strong-deploy#23]
`async` isn't correctly linked in package.json so `npm i strong-deploy` results in non-functioning application at the moment.

**Comment by rmg** [comment]
Thanks for the bug report.

Since you're the first to notice this I guess that tells us how many people are using these modules directly instead of through the `slc` wrapper from the [strongloop module](http://github.com/strongloop/strongloop).

**Comment by alexgorbatchev** [comment]
Not everyone would also be bothered to file an issue :) Thanks for fixing it!
