### ISSUE TITLE
slc deploy error on connect failure doesn't say what failed

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-deploy#27]
Related to #22, I suspect:

```
% slc deploy http://:8777    
Cannot access remote. Does git require authentication?
If authentication is required, credentials should be given in the URL.
```

"cannot access" is too generic, and not so helpful in this case.

It should say something about connection failed, and print the URL it was trying to connect to.

**Comment by rmg** [comment]
It is hard to divine those details based entirely off of `git`'s exit code.

**Comment by sam-github** [comment]
True, maybe we need to echo git push's stderr on failure?

**Comment by rmg** [comment]
Ready for release as soon as @cgole has had a chance to verify #29, then we'll do a minor release.
