### ISSUE TITLE
Add support for http+ssh:// mirroring the support in pmctl

### ISSUE THREAD

**Issue by rmg** [strongloop/strong-deploy#29]
See strongloop/strong-pm#128 for strong-pm's implementation.

**Comment by sam-github** [comment]
+1

**Comment by chandadharap** [comment]
I see that this is really necessary otherwise we cannot deploy over ssh, on a pm thats only accessible over ssh!!

**Comment by cgole** [comment]
verified.

**Comment by cgole** [comment]
still have to verify it user username and a vm. Only verified on locahost

**Comment by cgole** [comment]
verified 

Chandrikas-MacBook-Air:la chandrikagole$ export SSH_KEY=~/.ssh/sltest.pem  

Chandrikas-MacBook-Air:la chandrikagole$ SSH_USER=ec2-user slc deploy  http+ssh://ec2-54-244-202-181.us-west-2.compute.amazonaws.com:7777 ../la-1.0.0.tgz 
Deployed `../la-1.0.0.tgz` to `http+ssh://ec2-54-244-202-181.us-west-2.compute.amazonaws.com:7777`
