### ISSUE TITLE
add server response message for tarball post

### ISSUE THREAD

**Issue by sam-github** [strongloop/strong-deploy#33]
Similar to https://github.com/strongloop/strong-deploy/pull/28, but for tarballs.

Test with a raw non-npm tarball.

Consider checking that tarball is semi-well-formed (top-level directory is `package`) before pushing it.

**Comment by sam-github** [comment]
Related to https://github.com/strongloop-internal/scrum-cs/issues/118

**Comment by Setogit** [comment]
Looked at related modules such as strong-trace/index.js and strong-trace/bin/sl-deploy.js and got some basic idea on how it works.  Next, we need to clarify what is to be done.  pushed to Sprint 68.

**Comment by Setogit** [comment]
Spec: When tar push fails, present to the user a proper message which explains why it failed.  There are few failure conditions to consider: bad endpoint, server error (500, access denied, invalid type.  Changes will be in strong-deploy.
implementing...

**Comment by sam-github** [comment]
@Setogit The request was to add the server response method for ***tarball posts***.  You have a number  of changes here for local-deploy, but I don't see any for tarball.

For local-deploy, I added code in #28 to write the server response message on failure: https://github.com/strongloop/strong-deploy/blob/96c85ebf91778a41bafec6bbc88063091c40836d/lib/post-json.js#L49-L56

For tar ball posts, the server response message is not written: https://github.com/strongloop/strong-deploy/blob/more-error-msgs/lib/put-file.js#L37-L48

All that needs to be done here is to write the server response message on failure in put-file.js.

**Comment by Setogit** [comment]
connect to https://github.com/strongloop/strong-deploy/pull/40

**Comment by Setogit** [comment]
connect to https://github.com/strongloop/strong-pm/pull/184
