### ISSUE TITLE
Deploying from a local machine to a remote server using git crashes the StrongLoop Process Manager.

### ISSUE THREAD

**Issue by rvega** [strongloop/strong-deploy#50]
Hi. I'm trying to do a deploy as described [here](https://groups.google.com/forum/#!topic/loopbackjs/ssZOkzW3WkA).

With the process manager running in the remote server under systemd and with a ssh terminal following the output of `sudo journalctl -f` I did a deploy from my local machine using `export SSH_USER=*** && export  SSH_KEY=*** && slc deploy http+ssh://***:8701`.

On the local machine I got:

```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 638 bytes | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
To http://127.0.0.1:58967/api/services/1/deploy/default
   af58a4e..2ccd0d3  deploy -> deploy
```

And on the output of journalctl on the remote server I got:

```
Aug 12 17:01:49 ip-*** sshd[22461]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Aug 12 17:01:50 ip-*** sshd[22461]: Accepted publickey for *** from *** port 40840 ssh2: RSA ******
Aug 12 17:01:50 ip-*** sshd[22461]: pam_unix(sshd:session): session opened for user *** by (uid=0)
Aug 12 17:01:52 ip-*** sshd[22461]: pam_unix(sshd:session): session closed for user ***
Aug 12 17:01:54 ip-*** node[22368]: events.js:85
Aug 12 17:01:54 ip-*** node[22368]: throw er; // Unhandled 'error' event
Aug 12 17:01:54 ip-*** node[22368]: ^
Aug 12 17:01:54 ip-*** node[22368]: Error: spawn npm ENOENT
Aug 12 17:01:54 ip-*** node[22368]: at exports._errnoException (util.js:746:11)
Aug 12 17:01:54 ip-*** node[22368]: at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
Aug 12 17:01:54 ip-*** node[22368]: at child_process.js:1144:20
Aug 12 17:01:54 ip-*** node[22368]: at /home/***/.nvm/versions/node/v0.12.7/lib/node_modules/strong-pm/node_modules/strong-mesh-models/node_modules/
loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
Aug 12 17:01:54 ip-*** node[22368]: at process._tickDomainCallback (node.js:381:11)
Aug 12 17:01:54 ip-*** node[22368]: at process.<anonymous> (/home/***/.nvm/versions/node/v0.12.7/lib/node_modules/strong-pm/node_modules/strong-mesh
-models/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
Aug 12 17:01:54 ip-*** systemd[1]: strong-pm.service: main process exited, code=exited, status=1/FAILURE
Aug 12 17:01:54 ip-*** systemd[1]: Unit strong-pm.service entered failed state.
Aug 12 17:01:54 ip-*** systemd[1]: strong-pm.service holdoff time over, scheduling restart.
Aug 12 17:01:54 ip-*** systemd[1]: Stopping StrongLoop Process Manager...
Aug 12 17:01:54 ip-*** systemd[1]: Starting StrongLoop Process Manager...
Aug 12 17:01:54 ip-*** systemd[1]: Started StrongLoop Process Manager.
Aug 12 17:01:57 ip-*** node[22489]: sl-pm.js: StrongLoop PM v5.0.0 (API v6.1.0) on port `8701`
Aug 12 17:01:57 ip-*** node[22489]: sl-pm.js: Applications on port `3000 + service ID`
Aug 12 17:05:32 ip-*** sshd[22501]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Aug 12 17:05:32 ip-*** sshd[22501]: Received disconnect from ****: 11:  [preauth]
```

Then, the process manager is left running with no services and I have to manually go to /var/lib/strong-pm/svc/1/work/&lt;hash&gt;/ and do `slc start` so that my app runs.

Is this a bug on the deploy tools or maybe I'm not doing something correctly? Please advice.

**Comment by crandmck** [comment]
Note this issue was also reported on the forum: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/loopbackjs/ssZOkzW3WkA  Perhaps post resolution -- when we have one -- there as well (?)

**Comment by rmg** [comment]
You cannot use `nvm` to install `strong-pm` as a service. The problem is that when PM is running, it doesn't not actually have your global modules in `$PATH`, which is why it cannot find `npm`.

**Comment by rvega** [comment]
@rmg That makes sense. I symlinked all the executables from /home/user/.nvm/versions/node/0.12.7/bin to /usr/local/bin (which is in $PATH), verified that the symlinked binaries can be run by the strong-pm but now I can't even start the process manager. I'll try installing node from an up-to-date Debian repo and see how it goes.

**Comment by rvega** [comment]
I installed node as root using [these repos](https://github.com/nodesource/distributions#debinstall) and installed strong-pm as root with `npm install -g --unsafe-perm=true strong-pm`. And now everything works as expected.

I just noticed [this part of the docs](https://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-Makesureyouhavesufficientfileprivileges) where you explain about --unsafe-perm. Maybe this bit should be more visible in the docs, in the "installing strong-pm" section? The reason I installed with nvm in the first place was to avoid compiler errors when installing npm modules with sudo and I didn't know about the --unsafe-perm option.

Thanks for the help!  :)

**Comment by crandmck** [comment]
@rvega I added a note to [the docs](https://docs.strongloop.com/display/SLC/Setting+up+a+production+host#Settingupaproductionhost-Installnpmpackage).  Thanks for the suggestion.

**Comment by rmg** [comment]
@rvega the approach I use for StrongLoop's Docker and VM images is pretty straight forward, but not as convenient for upgrading:
```
mkdir -p /usr/local/src/node /usr/local/etc
curl -s http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-x64.tar.gz | tar -C /usr/local --strip-components 1 -xz -f -
curl -s http://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz | tar -C /usr/local/src/node --strip-components 1 -xz -f -
find /usr/local/src/node -not -name '*.h' -a -not -name '*.gypi' -a -not -type d -delete
echo "nodedir = /usr/local/src/node" > /usr/local/etc/npmrc
npm install -g npm && npm cache clear
```

It installs the official node binaries, and then extracts the source to /usr/local/src/node and points nodedir at it so that node-gyp doesn't need to download them (which is where permissions problems can come up).

The above is extracted from the Dockerfile for strongloop/strongbox:node - https://github.com/strongloop-community/strongbox/blob/master/node/Dockerfile. It is only meant to playing around, so you'd want to add shasum verification to the download steps for a more production quality version.

**Comment by pungoyal** [comment]
Could strongloop/strong-service-systemd#4 be related?
