### ISSUE TITLE
Support config file

### ISSUE THREAD

**Issue by listepo** [strongloop/strong-deploy#55]
As I see it is not possible to specify all in the configuration file and cause only one command

**Comment by rmg** [comment]
Can you elaborate on what you mean by "only one command"? Do you mean storing things like the URL and branch name in a config file so you don't need to specify them as arguments?

**Comment by listepo** [comment]
@rmg Yes, I would like to say one argument, like: http://pm2.keymetrics.io/docs/usage/deployment/
